"""new fields in user model

Revision ID: 64849b590d1a
Revises: ec06152042db
Create Date: 2024-08-23 18:15:21.517720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64849b590d1a'
down_revision = 'ec06152042db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
